require "active_support/core_ext/string/strip"
require "octokit"

require "ellen"
require "ellen/github/actions/base"
require "ellen/github/actions/close_issue"
require "ellen/github/actions/create_issue"
require "ellen/github/actions/remember"
require "ellen/github/version"
require "ellen/handlers/github"
